@host=http://localhost:8080

###
GET {{host}}/todos

###
GET {{host}}/todos?offset=1&limit=2

###
# @name newTodo
POST {{host}}/todos
Content-Type: application/json

{
    "title": "Learn Rust",
    "notes": "Rust is a systems programming language that runs blazingly fast, prevents segfaults, and guarantees thread safety.",
    "assigned_to": "Rainer",
    "completed": false
}

###
@addedTodoId={{newTodo.response.body.$.id}}
GET {{host}}/todos/{{addedTodoId}}

###
@addedTodoId={{newTodo.response.body.$.id}}
PATCH {{host}}/todos/{{addedTodoId}}
Content-Type: application/json

{
    "completed": true
}

###
@addedTodoId={{newTodo.response.body.$.id}}
DELETE {{host}}/todos/{{addedTodoId}}

###
POST {{host}}/todos/persist
