GET http://localhost:4000/health_1

###
GET http://localhost:4000/health_2

###
GET http://localhost:4000/health_3

###
GET http://localhost:4000/health_4

###
POST http://localhost:4000/heroes
Content-Type: application/json

{
    "name": "Superman",
    "firstSeen": "1935-01-01T00:00:00Z",
    "canFly": true,
    "realname": "Clark Kent",
    "abilities": "super strong, can disguise with glasses"
}

