spin_manifest_version = "1"
authors = ["Rainer Stropek"]
description = "Todo API in spin"
name = "todo-spin"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "todo-spin"
source = "target/wasm32-wasi/debug/todo_spin.wasm"
allowed_http_hosts = []
[component.trigger]
route = "/todos/..."
[component.build]
command = "cargo build -p todo-spin --target wasm32-wasi"
watch = ["src/**/*.rs", "Cargo.toml"]
