[package]
name = "todo-logic"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version= "1", features = ["fs"] }
thiserror = "1"
