[package]
name = "todo-warp"
version = "0.1.0"
edition = "2021"

[dependencies]
warp = "0.3"
tokio = { version = "1", features = ["full"] }
todo-logic ={ path = "../todo-logic" }
simplelog= "0"
log = "0.4"
